name: CRONO
description: Aplicativo para cronograma capilar.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  footer:
  # flutter_form_builder: ^3.4.1
  cupertino_icons: ^1.0.2
  google_fonts: ^2.0.0
  syncfusion_flutter_calendar: ^19.1.65
  shared_preferences: ^2.0.6
  firebase_core: ^1.2.0
  cloud_firestore: ^2.2.0
  firebase_storage: ^8.1.0
  firebase_auth: ^1.2.0
  table_calendar: ^3.0.0
  intl: 


  
  # flutter_widget_from_html: ^0.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/ 
